name: LibreELEC Build - Ultra Minimal (Manual Only)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual minimal build'
        required: false
        default: 'Manual minimal test'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget

      - name: Clone LibreELEC
        run: |
          cd libreelec-custom-build
          git clone --depth 1 --branch libreelec-12.0 https://github.com/LibreELEC/LibreELEC.tv.git
          ls -la LibreELEC.tv/

      - name: Apply Fixes
        run: |
          cp scripts/comprehensive-package-fix.sh libreelec-custom-build/
          cd libreelec-custom-build
          chmod +x comprehensive-package-fix.sh
          ./comprehensive-package-fix.sh LibreELEC.tv

      - name: Test Complete
        run: |
          echo "✅ Ultra-minimal LibreELEC workflow completed successfully!"
          echo "This confirms the workflow system is working."
