name: LibreELEC Build - Minimal Test

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test script access
        run: |
          echo "Testing script access..."
          ls -la scripts/
          echo "comprehensive-package-fix.sh exists: $(test -f scripts/comprehensive-package-fix.sh && echo 'YES' || echo 'NO')"
          echo "universal-package-downloader.sh exists: $(test -f scripts/universal-package-downloader.sh && echo 'YES' || echo 'NO')"

      - name: Test basic build setup
        run: |
          echo "Testing basic build setup..."
          cd libreelec-custom-build
          echo "libreelec-custom-build directory contents:"
          ls -la

      - name: Test comprehensive package fix script
        run: |
          echo "Testing comprehensive package fix script..."
          cd libreelec-custom-build
          cp ../scripts/comprehensive-package-fix.sh .
          cp ../scripts/universal-package-downloader.sh .
          chmod +x comprehensive-package-fix.sh universal-package-downloader.sh
          echo "Scripts copied and made executable"
          ls -la *.sh
