name: Test Runner Setup

on:
  workflow_dispatch:

jobs:
  test-basics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Test basic commands
      run: |
        echo "=== Basic System Info ==="
        uname -a
        whoami
        pwd
        df -h
        
    - name: Test Docker availability
      run: |
        echo "=== Docker Info ==="
        docker --version || echo "Docker not available"
        docker info || echo "Docker daemon not accessible"
        
    - name: Test privileged operations
      run: |
        echo "=== Testing Privileged Mode ==="
        sudo whoami || echo "Sudo not available"
        ls -la /dev/ | head -5
        
    - name: Test build prerequisites
      run: |
        echo "=== Build Prerequisites ==="
        which debootstrap || echo "debootstrap not found"
        which qemu-user-static || echo "qemu-user-static not found" 
        which parted || echo "parted not found"
        which kpartx || echo "kpartx not found"
        
    - name: Simple artifact test
      run: |
        echo "Test artifact content" > test-artifact.txt
        echo "Build completed at: $(date)" >> test-artifact.txt
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-artifact
        path: test-artifact.txt
        retention-days: 1
