name: Test Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-workflow.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test step
        run: |
          echo "Testing basic workflow functionality"
          echo "This should work if there are no fundamental issues"
